//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTipoPublicacao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTipoPublicacao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model.Resources.ResTipoPublicacao", typeof(ResTipoPublicacao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artigos  completos publicados em periódicos.
        /// </summary>
        internal static string ArtigosCompletosPeriodicos {
            get {
                return ResourceManager.GetString("ArtigosCompletosPeriodicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capítulos de livros publicados.
        /// </summary>
        internal static string CapitulosLivros {
            get {
                return ResourceManager.GetString("CapitulosLivros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livros publicados/organizados ou edições.
        /// </summary>
        internal static string LivrosPublicados {
            get {
                return ResourceManager.GetString("LivrosPublicados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumos expandidos publicados em anais de congressos.
        /// </summary>
        internal static string ResumosExpandidos {
            get {
                return ResourceManager.GetString("ResumosExpandidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumos publicados em anais de congressos.
        /// </summary>
        internal static string ResumosPublicados {
            get {
                return ResourceManager.GetString("ResumosPublicados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabalhos completos publicados em anais de congressos.
        /// </summary>
        internal static string TrabalhosPublicadosAnais {
            get {
                return ResourceManager.GetString("TrabalhosPublicadosAnais", resourceCulture);
            }
        }
    }
}
